### ISSUE TITLE
Token expiry issue 1hr after the process starts

### ISSUE THREAD

**Issue by siddhu268** [mulesoft-catalyst/metrics-accelerator#111]
Our platform contains 2 business groups, 100+ APIs, 100+ exchange assets. It usually takes 20 mins to complete the entire process. At times, platform APIs performance goes down and it takes more time than usual to respond. To avoid timeouts, I have increased the timeouts, decreased the concurrency, added until-successful on HTTP requests. But due to the increased timeouts, the whole process execution spills beyond 1 hour.

Token fetched initially seems valid for 1 hour and any calls that happens beyond 1hr ends up with Unauthorized issue.
Can this be handled? Please.

**Comment by panizzag** [comment]
Hi @siddhu268  !
Thanks for collaborating on opening this issue. Two things I think you can do to manage this scenario:
- Configuration: Setting the session timeout in Anypoint Platform. Default is 60 minutes and the maximum is 180 minutes. Take into account this change is a global change and may impact session spanning for other users as well (Please refer to https://docs.mulesoft.com/access-management/organization#manage-master-organization-settings for further details)
- Implementation: you can obtain a new token when you get a 401 by catching the exception and placing a flow ref to 'api-call-coreservices-login-flow' 
Hope this helps!

Best,
GP

**Comment by siddhu268** [comment]
Hi @panizzag,

Thanks for the suggestion. I had already raised for approvals for changes with the first approach.
My intention in raising the issue was that if the second approach is implemented, it would be helpful for the global audience using this accelerator.

Thanks Again for putting this together 
-Siddardha Sarabu
