### ISSUE TITLE
connected-app-credentials auth mode can't gather all the metrics 

### ISSUE THREAD

**Issue by leozh-mule-oa** [mulesoft-catalyst/metrics-accelerator#49]
If I use platform-credentials auth mode with org admin role, I can get all the platform metrics back. However, if I use connected-app-credentials auth mode with all the defined scopes, I can't get all the metrics. The following is the log in the console. Even I add much more scopes for the connected app, I still can't get all the metrics especially Anypoint MQ.

INFO  2020-10-08 22:10:16,150 [[MuleRuntime].cpuLight.03: [metrics-framework-m4].aggregator-platform-metrics-org-flow.CPU_LITE @7e8f1396] [event: 91f3c1c0-09d4-11eb-a5fe-38dead248cc8] org.mule.runtime.core.internal.processor.LoggerMessageProcessor: API Client Metrics won't be collected: collector not enabled or not supported for the platform deployment model or authentication mode.
INFO  2020-10-08 22:10:16,150 [[MuleRuntime].cpuLight.08: [metrics-framework-m4].api-call-coreservices-environments-flow.CPU_LITE @4e97aa29: [metrics-framework-m4].aggregator-platform-metrics-org-flow.CPU_LITE @7e8f1396] [event: 91f3c1c0-09d4-11eb-a5fe-38dead248cc8] org.mule.runtime.core.internal.processor.LoggerMessageProcessor: Anypoint MQ Metrics won't be collected: collector not enabled or not supported for the platform deployment model or authentication mode.
INFO  2020-10-08 22:10:16,178 [[MuleRuntime].cpuLight.07: [metrics-framework-m4].aggregator-platform-metrics-org-flow.CPU_LITE @7e8f1396: [metrics-framework-m4].aggregator-platform-metrics-coreservices-flow.CPU_LITE @365f8247: [metrics-framework-m4].aggregator-platform-metrics-coreservices-flow.CPU_LITE @365f8247] [event: 91f3c1c0-09d4-11eb-a5fe-38dead248cc8] Coresercices::Usage not supported when authentication mode is connected-app-credentials:

**Comment by DavoCoder** [comment]
This is documented here: https://github.com/mulesoft-catalyst/metrics-framework-m4#limitations there are some limitations driven by some Anypoint Platform APIs - nothing we can do until this is supported by APIs
