### ISSUE TITLE
Elastic Exported Fields

### ISSUE THREAD

**Issue by joshjacques** [mulesoft-catalyst/metrics-accelerator#51]
I'll first start by saying this is more of a request than an issue as I'm just looking for what field names will be indexed into elasticsearch or more specifically is all of the data time series?

I'm considering using data streams for this, but one of the requirements is each message needs to have an @timestamp field mapped as a date.

Again, looking for a list of fields OR if each message has an @timestamp field.

Thanks

**Comment by gozdy** [comment]
Hi @joshjacques , the data provided by the MA and that is exported to ELK is one data set that includes a date field that could work as the @timestamp field for data streams. We have not tested data streams but I don't see any issue in the data format that is currently provided.

Let me know if this helps and the issue can be resolved!

**Comment by panizzag** [comment]
Closing this one due to inactivity. Please @joshjacques, open a new issue if you need further assistance. Thanks.
