### ISSUE TITLE
Client App API limit can only be 250 - higher client app limits should be accomodated

### ISSUE THREAD

**Issue by msunkrish** [mulesoft-catalyst/metrics-accelerator#63]
https://github.com/mulesoft-catalyst/metrics-accelerator/blob/a3133b83a61e4b30203e7f9d0a84f7b9591e2f31/src/main/mule/sources/anypoint/platform/apis/api-call-api-platform.xml#L27

On the platform API for /applications - the response payload contains a field called  "total" that could rather be used to collect the consolidated data for Client Applications

**Comment by damiancalabresi** [comment]
Thanks @msunkrish , I'll look at this and analyze if the pagination can be improved.

**Comment by damiancalabresi** [comment]
This issue has been resolved in the release 1.6.0
