### ISSUE TITLE
Loader default flow for benefits should call loader benefits default flow

### ISSUE THREAD

**Issue by kgaurav-mule** [mulesoft-catalyst/metrics-accelerator#64]
In loader-router.xml, the default route of loader-benefits-default flow calls loader-default for platform metrics and not platform benefits. This should be changed to call loader-benefits-flow.

Screenshot attached
![2021-01-07_20-13-52](https://user-images.githubusercontent.com/28023463/103962499-169d9d00-5125-11eb-8ef4-53f4415d71f9.png)

**Comment by damiancalabresi** [comment]
It looks like a minor change. @olamiral-mulesoft will take a look at it.

**Comment by DavoCoder** [comment]
Fixed, will be available in the next release iteration: v1.5.1, v1.6.0
