### ISSUE TITLE
No configuration of excluded environments possible(?)

### ISSUE THREAD

**Issue by desombre** [mulesoft-catalyst/metrics-accelerator#86]
Hello,

I want to explicitly exclude environments, currently I can't find a way to configure this. Is there a way I missed?

**Comment by panizzag** [comment]
Hi Philipp @desombre,
You're right. There is currently no setting to filter by the environment. Could you please define a user story/business case to analyze this new feature? Do you want it to be filtered dynamically (for example through a queryParam) or do you want to define a kind of ACL where you specify which environments you want to allow/disallow? By Anypoint Platform module (APIM, ARM)?
Thanks.

**Comment by panizzag** [comment]
Closing this one due to inactivity during the last 6 months. Please @desombre , if you're still interested in getting this feature, please send a new issue describing the information requested above.
